services:
  mongodb:
    image: mongo:8.0 # Database stable image
    container_name: chat_app_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_chat_data:/data/db

volumes:
  mongo_chat_data:
    driver: local
